### PR TITLE
implemented results not found

### PR DESCRIPTION
**Pull request by crpkry13i**
Implements "results not found" when user searches for something that doesn't exist in DB.

### CODE REVIEW

**Comment by ghost** [comment]
Got it, will review in a sec.

**Review by ghost — CHANGES_REQUESTED** [review]
Let’s try this again, shall we?

**Review by crpkry13i — COMMENTED** [review]
Fixed

**Review by crpkry13i — COMMENTED** [review]
Attempt at fixing empty result 01

**Review by crpkry13i — COMMENTED** [review]
Test

**Review by crpkry13i — COMMENTED** [review]
Attempt at empty results fix

**Review by ghost — APPROVED** [review]
Approved! Awesome job 😀

**Pull request merged**
